# Generated by Django 4.1.3 on 2022-11-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_prodb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodb',
            old_name='cat',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='prodb',
            old_name='proname',
            new_name='pnam',
        ),
    ]
