# Generated by Django 4.1.3 on 2022-11-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_rename_cat_prodb_name_rename_proname_prodb_pnam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodb',
            old_name='name',
            new_name='category',
        ),
    ]
