# Generated by Django 4.1.3 on 2022-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_rename_name_prodb_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodb',
            old_name='pnam',
            new_name='pname',
        ),
    ]
